name: e_tutoring
description: E Tutoring Application

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^8.8.1
  
  scrollable_positioned_list: ^0.1.7
  http: ^0.13.3

  # store & load data securely
  flutter_secure_storage: ^4.2.0
  
  intl: ^0.17.0

  move_to_background: ^1.0.2

  # mockito for test
  # mockito: ^5.0.10

  email_validator: ^2.0.1

  table_calendar: ^3.0.0

  # state management
  provider: ^4.3.3

  flutter_local_notifications: ^5.0.0+4
  firebase_core: ^1.1.0
  firebase_messaging: ^10.0.2


dev_dependencies:
  
  flutter_test:
    sdk: flutter
  
  # mockito for test
  mockito: ^5.0.10
  build_runner: ^2.0.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/img/pro-background.png
   - assets/img/onboard-background.png
   - assets/img/logo-android.png
   - assets/img/logo-ios.png
   - assets/img/logo-argon.png
   - assets/img/profile-screen-avatar.jpg
   - assets/img/profile-screen-bg.png
   - assets/img/register-bg.png
   - assets/img/chat-avatar.jpeg
   - assets/img/argon-logo.png
   - assets/img/argon-logo-onboarding.png
   - assets/img/background-myunito.jpg
   - assets/img/tutoring.jpg
   - assets/img/tutoring-2.jpg
   - assets/img/logo_size.jpg
   - assets/img/logo_size_1.jpg
   - assets/img/logo_size_2.jpg
   - assets/img/logo_size_invert.jpg
   - assets/img/img_avatar.png
   - assets/img/user-profile.jpg
   - assets/img/image.jpg

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 200
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 600

